### ISSUE TITLE
Citing

### ISSUE THREAD

**Issue by seabbs** [fauvernierma/survPen#11]
As part of this review openjournals/joss-reviews#1434

I recommend adding citation information to the package (will need updating upon JOSS acceptance) and to the readme. 

Examples for [package citation](https://github.com/seabbs/getTBinR/blob/master/inst/CITATION) and [readme](https://github.com/seabbs/getTBinR/blob/c43f2dc20ac036d6cc93ec32bb9b33f9b4399f28/README.Rmd#L126)

You may also want to say when the package should be referenced versus the methods paper currently under review (or both). If both you need to more explicitly point to the methods paper as something that needs to be cited.

**Comment by fauvernierma** [comment]
I added a package citation 72852b9ec56fec8180b8c4c8f6c7dc985cd5b10f (but I am not sure of how to deal with group author) and a citation header in the readme 04183aed8cb56a8a17b89f0bf9e5841e4dd26523

**Comment by seabbs** [comment]
That looks good to me. Do you want people who use the package to also cite the methods paper - could be a good idea to mention in the readme. 

* [*optional*] If you change your README to a Rmd rather than a MD you can print the output of the citation. Target output needs to be a github_document.

**Comment by fauvernierma** [comment]
Thank you, 

It should be ok now 922326e006138a4714044ed8432ee6f8cf970dfb

**Comment by seabbs** [comment]
Nice. 

It looks like you need to rebuild the package and knit the readme again as it currently shows the wrong citation.

There is also a problem with the formatting your md - perhaps from kniting? it is showing the ouput type at the beginning.

**Comment by fauvernierma** [comment]
Hi,

I think everything is in order now a7b85eb8a84507ed2399494338851f4800bd2efb

Thank you

**Comment by seabbs** [comment]
Looks good.
