### ISSUE TITLE
Binder

### ISSUE THREAD

**Issue by seabbs** [fauvernierma/survPen#12]
As part of this review openjournals/joss-reviews#1434

I would love to see a launch with binder option to allow people to start playing around with the package as quickly as possible. 

"Binder allows you to create custom computing environments that can be shared and used by many remote users. It is powered by BinderHub, which is an open-source tool that deploys the Binder service in the cloud. One-such deployment lives here, at mybinder.org, and is free to use."

See [docs](https://mybinder.readthedocs.io/en/latest/) for more information. Set up can be a bit of a fiddle if not used to docker so you may want to borrow from [another](https://github.com/seabbs/getTBinR/blob/master/binder/Dockerfile) implementation. 

Once everything is set-up just added a button to the readme. Along the lines of, 

[![badge](https://img.shields.io/badge/Launch-survPen-lightblue.svg)](https://mybinder.org/v2/gh/fauvernierma/survPen/master?urlpath=rstudio)

**Comment by fauvernierma** [comment]
Hi,

Binder seems to be working 3c7517677b6f593a42bebec781c0e9ad6684288e

However I find it a bit slow, is it normal in your experience ? 
This can be related to the connection I have at work though :)

**Comment by seabbs** [comment]
Looks good to me. Thanks for adding this - a little bit of a personal passion for me. 

Lagging or slow compute? Compute will be slow as they assign you a very small amount of a vCPU. Shouldn't be too laggy though.

**Comment by seabbs** [comment]
Just run through the vignette and yes it is pretty slow. Not something for serious work but good for discovery.
