### ISSUE TITLE
inline code formatting

### ISSUE THREAD

**Issue by corybrunson** [fauvernierma/survPen#13]
The [thorough vignette](https://htmlpreview.github.io/?https://github.com/fauvernierma/survPen/blob/master/inst/doc/survival_analysis_with_survPen.html) contains much _italicized inline code_ that would be easier to read / scan / refer back to if formatted as `verbatim inline code`. It would also help easily distinguish the code from the mathematical expressions. This is a minor point, i know, but good formatting becomes all the more valuable in lengthier documents!

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/1434)._

**Comment by fauvernierma** [comment]
Hi,

This should be ok now d0d6ea8dde60e2779633d051b5cfa2b2be6214c5,  f372926a9cda3cf1739566a8decccbb5dcc5a247. Indeed, it looks much better now ;)

**Comment by corybrunson** [comment]
Yes, i found the readability much improved. Thank you!
