### ISSUE TITLE
function instr

### ISSUE THREAD

**Issue by abdoudesouki** [fauvernierma/survPen#24]
@fauvernierma 
code copied from answer without giving link to it, in package survPen
https://stackoverflow.com/a/33005653/5421090
Please correct that.

**Comment by fauvernierma** [comment]
Sorry for that, this is clearly not good practice

Just added the source material in the following commit
14d9a132a5a8b946cfbb74fde79a555db6bb5b02

This will appear in the CRAN version as soon as I upload a new survPen version

Have a great day
