### ISSUE TITLE
Package release versioning

### ISSUE THREAD

**Issue by seabbs** [fauvernierma/survPen#3]
As part of this review openjournals/joss-reviews#1434

It would be great to see explicit versioning of your package releases. This can be done with a tool like [Zenodo](https://zenodo.org) and Github tags. This is also nice to have as it gives you a software DOI to refer to on top of the JOSS paper DOI (allowing the actual version of the package used to be referenced)

As for the license see [here](https://github.com/seabbs/getTBinR) for an example of this (apologies for the self-referencing).

For Zenodo the steps are as follows:

* Sign up to Zenodo and turn of archiving for this repository
* Make a release using GitHub tags - this should then be automatically tagged by Zenodo
* Add the markdown badge to your readme (either using the version badge or the most up to date DOI badge)
* Continue to make tags as new versions of the package are released (perhaps adding your news into the details section).

**Comment by fauvernierma** [comment]
Thank you @seabbs for clearly explaining the different steps.

As I understand from the other JOSS reviews that I read, the Zenodo archive is usually done on acceptance. So should I do it now ?

**Comment by seabbs** [comment]
No problem. 

Hmm I am not sure that is the case but you could be correct.

It is generally good practise to have set-up. When the paper is accepted you can then tag and archive a new version. I think that is the best way to go. 

Basically, you should be tagging every major release. People can then reference the version of your software that they are using.

**Comment by fauvernierma** [comment]
Ok thank you

I think it is set-up now, I just added Zenodo DOI to the README file

**Comment by fauvernierma** [comment]
The corresponding commit is e8a45e32c5caff36b1c6ed3cade787433df3c584

**Comment by seabbs** [comment]
Could you possibly wait for me to review these changes before closing? It will help me keep track of what is going on.

**Comment by fauvernierma** [comment]
Sorry, maybe it is best if I let you close the issues :)
