### ISSUE TITLE
Authorship

### ISSUE THREAD

**Issue by seabbs** [fauvernierma/survPen#4]
As part of this review openjournals/joss-reviews#1434

I am only seeing GitHub commits from @fauvernierma? 

From the paper I am assuming that the other authors are thesis advisors etc. - could you please clarify their individual contributions. 

In a normal paper, this is the sort of thing that would be listed at the end but I am not sure that JOSS stipulates this.

**Comment by seabbs** [comment]
Dealt with in the review thread. Could you possibly post answers here so I can keep track :)

**Comment by fauvernierma** [comment]
Ok sorry,

As explained in the review thread :
the four other authors/contributors and I are part of a survival working group within our research department. Two of them (Laurent Remontet and Nadine Bossard) are indeed my thesis advisors.
Laurent Roche and Laurent Remontet are cited as authors as they intervened in the core development of the package (especially in linear algebra and matrix derivatives).
As for Zoé Uhry and Nadine Bossard, they contributed to the writing of the documentation and gave important pieces of advice relative to the package functionalities.

**Comment by seabbs** [comment]
Awesome thank you :)
