### ISSUE TITLE
Paper: Statement of need + who is this for

### ISSUE THREAD

**Issue by seabbs** [fauvernierma/survPen#5]
As part of this review openjournals/joss-reviews#1434

At the moment I feel like readers need to look over the whole paper to get a good idea of why the package is needed. It would be great if the need could be a little clearer in the first paragraph. There may also be an issue for people who don't know why splines are a good choice. 

So my reading of the need for this package is that, 

1. In survival analysis, we need to fit models that account for various confounders with potential complex non-linear effects that are not known a priori
2. Penalised regression splines represent an appealing solution (explain in more detail?)
3. Current implementations are slow and/or unstable. `survPen` represents a fully automated, fast, and stable tool set. 

Could you condense this (improve my blatherings!) for the opening paragraph of the paper? 

I am also not seeing anything referencing who this is for explicitly - perhaps add a sentence. The examples etc. make it clear that it can be used by epidemiologists with survival data but potentially has quite a few other uses?

**Comment by fauvernierma** [comment]
I just added the required parts bba311cd201bd5fdd8aa4631671527c059503f6e

If it is ok with you, I will add something similar in the README as well as in the DESCRIPTION file

Thank you

**Comment by seabbs** [comment]
Great thanks - very good. 

Yes it would be nice to see something similar in the intro and description.

**Comment by fauvernierma** [comment]
Hi, I added the required parts in the README and the DESCRIPTION file
00eed484685070a4fc6faefdacbbe8bd0177d627
799451abe2ae1c58a2fc577cadfaf7aefb7e85c8

Do we consider this issue closed ?

**Comment by seabbs** [comment]
Yes - good job 👍

**Comment by seabbs** [comment]
These are great additions. However, I think these really resolve #15 rather than this issue. This was more looking at clarifying the first paragraph of the JOSS paper.

**Comment by fauvernierma** [comment]
I agree about #15 but I am not sure what is missing to resolve #5
Did not bba311cd201bd5fdd8aa4631671527c059503f6e solve the issue ?

Thank you

**Comment by seabbs** [comment]
Missed that change - looks good to me closing this.
