### ISSUE TITLE
References

### ISSUE THREAD

**Issue by seabbs** [fauvernierma/survPen#6]
As part of this review openjournals/joss-reviews#1434

* Your second reference has no DOI
* [*optional*] For the links within the paper consider using markdown links rather than explicitly writing out (cleaner)

**Comment by fauvernierma** [comment]
If I am right, the missing DOIs only concern Fauvernier2019, R and Wood2017 and I think it is normal that they do not have one : the first one is my submitted article, the second one is for the R software and the third has a ISBN number

Is there something that I am missing ?

Concerning the links, isn't the @ considered a markdown link ?

Thank you and sorry If my questions seem a bit naive

**Comment by seabbs** [comment]
I only meant Fauvernier2019 for the DOI but based on what you have said I guess this is under review. It seems a shame that this isn't available to support the package as it seems so critical. As I mentioned in the other issue have you considered preprinting. 

For the links I meant the GitHub links etc not the referencing - sorry for the confusion. I was suggesting that you use markdown [links](https://github.com) rather than pasting the full link (i.e https://github.com). This is more of a style consideration so don't worry if you disagree.

If not open to preprinting then I am happy for you to close this issue.

**Comment by fauvernierma** [comment]
Ok, thank you

I admit that the co-authors and I have not considered preprinting but hopefully the article will be accepted soon and I will be able to properly cite it. 

Concerning the links, I made the following commit 1e206d5383f759e3cfe1f6417669a4e3bf9f6abc

**Comment by seabbs** [comment]
Okay great - happy to close this issue. 

Just a final note: I would really strongly urge you to preprint if at all possible. You can use [this](http://sherpa.ac.uk/romeo/index.php) to check the preprint policies at your target journal.
