### ISSUE TITLE
Community guidelines

### ISSUE THREAD

**Issue by seabbs** [fauvernierma/survPen#7]
As part of this review openjournals/joss-reviews#1434

As an open source tool this needs clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

A good way to do this is to steal a page from the tidyverse toolbox. 

I would like to see the following,

1. Information on how to contribute in the README.
1. Link to code of conduct in the readme
1. Code of conduct, contributing and support either in the readme or as separate markdown documents. 

See [here](https://github.com/seabbs/getTBinR/tree/master/.github) and [here](https://github.com/seabbs/getTBinR/blob/master/README.md) (again! :smile:) for my tidyverse inspired approach.

**Comment by fauvernierma** [comment]
I added a Contributing section 8a72018ea3852dae65949c0a6195db4056729282 in the readme as well as the required [files](https://github.com/fauvernierma/survPen/tree/master/.github)

**Comment by seabbs** [comment]
Contributing section looks good - are you interested in user submitted data? If not maybe delete that part!

Files all look good 👍 

By the way, it might be a good idea to increment your package version for all these changes and add the updates to your news file under the new version title.

**Comment by seabbs** [comment]
Just noting that this can be closed if you 1.) want users to submit data or 2.) remove that from the contributing statement. 

Have a good weekend :smile:

**Comment by fauvernierma** [comment]
The data part from the contributing statement is ok for me

Thanks and good weekend to you too
