### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by seabbs** [fauvernierma/survPen#9]
As part of this review openjournals/joss-reviews#1434

As I said in the review thread the vignette for this package is fantastic. Your within R function documentation is also very good (👍) - `survPen` has some of the best documentation I have ever seen. However, I think a few small changes could lead to some big usability improvements.

1. Flesh out the readme. I really like to see a detailed readme with some quick details about the package. 
   * Why this package
   * Installation (you have this :smile:)
   * Some quick start information. The key functions and/or an example of using the package to solve some issue. This is effectively selling the package to the user. 
   * As mentioned in other issues add test badges along with other badges giving release information etc. (*optional*). See [here](https://github.com/seabbs/getTBinR/blob/master/README.Rmd).
2. (*optional*) Personally I think I would split the current readme into separate documents - as it currently stands it is a little intimidating! 
3. I would really like to see an example of using this package versus using some of the other available packages to solve the same issues. This would really help the potential user to understand why what your offering is so much better. It would also act as a nice check that this packages produces similiar results (hopefully much faster) to other more established packages. 
4. Package description needs to be more detailed. Consider using the first paragraph summarising the package from the readme.
5. Package website. I find looking at package documentation + getting a feel for how the package works to be much easier if the package has a website (i.e [`getTBinR`](https://www.samabbott.co.uk/getTBinR/)). This is particularly helpful for understanding what functions the package offers (similar to the manual PDF). Setting up a website is very straightforward so I would very much recommend it. Steps, 
   * Install `pkgdown` and see [docs](https://pkgdown.r-lib.org).
   * Set up the  `_pkgdown.yml` either using [`usethis`](https://usethis.r-lib.org/reference/use_pkgdown.html) or with an [example](https://github.com/seabbs/getTBinR/blob/master/_pkgdown.yml).
   * Build the website using `pkgdown::build_site()` (can also build and deploy on travis - see [here](https://pkgdown.r-lib.org/articles/pkgdown.html#configuration).
   * Iterate and improve. 

I realise this looks like a lot to do but really only small changes are needed. In general docs are great!

**Comment by corybrunson** [comment]
I agree with most of what @seabbs has suggested, but i'd like to expand on (2): The original long vignette builds incrementally upon the analysis of a single data set, which i find useful, and i would suggest keeping something like it as a technical overview. It would be extremely helpful to _also_ include smaller vignettes that allow users to quickly learn the essentials of specific techniques.

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/1434)._

**Comment by seabbs** [comment]
@corybrunson - that makes a lot of sense to me.

**Comment by fauvernierma** [comment]
Hi,

Most of what was required concerning this issue has been dealt with and there seems to be two main points left : the website and the smaller vignettes.
To me, these two points feel a bit minor relative to what the documentation has to offer. Concerning the only vignette I understand it can look a bit intimidating but it is exhaustive and its format (html) makes it easy to navigate into the different sections. That is the reason why I find redundant and tiresome to split the current vignette into smaller ones. And to be honest I feel the same about the website (to me the website is the github page).

**Comment by seabbs** [comment]
The following are things that I expect a good modern package to have:

1. A quick start guide in the README
2. A comparison of the package compared to others linked from the documentation or in the documentation. 
3. Package website

Happy for you to have a single vignette. Personally, I think this may scare off some users but this is a personal choice on your part. 

A `pkgdown` site is great as it gives a much better place to explore function documentation. As they are so standard across packages it also makes it easier for users to explore the functionality of your package. 

What do you think @corybrunson? Happy to skip any/all.

**Comment by corybrunson** [comment]
I agree with @seabbs about the utility of including, e.g., a quick start in the README as well as the sort of thorough vignette @fauvernierma has already written. But i think we're also on the same page about the criteria for recommendation and acceptance to JOSS. The documentation is there, so i consider that element of the review process complete. The developers (or users!) can augment it with intros or shorter vignettes in future.

However, if the package makes claims to improved performance over alternatives (see #10), then these must be substantiated. My understanding is that this will have been done in the paper, once published. (It would then of course need to be available in some form for free and hyperlinked from the README or vignette.) Alternatively, the demonstration could be part of the package, with expository text and output along with system specs, which would most naturally be done as a vignette.

**Comment by fauvernierma** [comment]
Thank you both for these pieces of advice

@corybrunson, concerning the performance claims, we totally agree. I have just returned the corrected proofs along with the code associated with the paper. As soon as the Journal gives me the final link to access the code I will add it into github

Thanks again

**Comment by fauvernierma** [comment]
Hello,

I just added a Quick Start with a couple of figures 90349fdc68d8295894429957f2d13084e559fd47

**Comment by corybrunson** [comment]
The Quick Start is immensely helpful! Thanks for that @fauvernierma. My only suggestion is to add a concluding sentence after the excess hazard surface, to make the takeaway explicit and to help separate the quick start from the next section (contributing). (This is not a requirement for recommendation, just a stylistic suggestion.)

**Comment by fauvernierma** [comment]
You are rigth this is better now f1e6e6ac06c838679d858432de26244db0f16335

Thanks

**Comment by seabbs** [comment]
Quickstart is a really nice addition thanks @fauvernierma. The final thing is a link to the performance claims in the documentation. 

Website is optional (but encouraged).

**Comment by seabbs** [comment]
Sorry just noticed that both the binder and appveyor badges have been dropped from the README - could you clarify why @fauvernierma?

**Comment by fauvernierma** [comment]
That's clearly a mistake on my part, sorry (wrong copy and paste I guess)

They are back again bd70d4178efc46e64e4eb0f056909adeb294d9c1

Thanks
